[programs.localnet]
ticket_program = "3P5yoyrBoSCRnyJKHZW227EDhbMxnFFbf7kEMNFt7ZTt"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[build]
docker = false