[programs.localnet]
ticket_program = "UTitk8h1unBx2KrKdUiJ4iwsPYVESyCWbsooTQfivJV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[build]
docker = false