[programs.localnet]
ticket_program = "8Ed9Jimrz4istGe3C9QViAUsvBxTUof7MiFyJsAmpVy1"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[build]
docker = false